model:
  yolo:
    version: "v5"
    weights: "yolov5s.pt"
    conf_thres: 0.3
    iou_thres: 0.5
    
  rcnn:
    backbone: "vgg16"
    weights: null
    conf_thres: 0.3
    nms_thres: 0.5
    
ensemble:
  detection_weights: [0.4, 0.6]  # YOLO, RCNN
  classification_weights: [0.3, 0.7]
  
training:
  batch_size: 16
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0005
  
evaluation:
  metrics: ["mAP", "precision", "recall"]
  size_thresholds:
    small: 32
    medium: 96
    large: 256