# configs/models/faster_rcnn.yaml
detector_type: 'faster_rcnn' # detector_type

device: "cuda"  # 또는 "cpu"
backbone:
  type: "vgg16"  # ["vgg16", "resnet50", "efficientnet"]
  pretrained: true
  freeze: true
  trainable_stages: [4, 5]  # 선택적으로 특정 스테이지만 학습 가능하게 설정
weights: null
num_classes: 81  # COCO classes + 1 background class
model:
  num_classes: 91
  conf_threshold: 0.3
  nms_threshold: 0.5
  min_size: 800
  max_size: 1333
  box_detections_per_img: 100
rpn:
  anchor_sizes: [32, 64, 128, 256, 512]
  anchor_ratios: [0.5, 1.0, 2.0]
  pre_nms_top_n_train: 2000
  pre_nms_top_n_test: 1000
  post_nms_top_n_train: 2000
  post_nms_top_n_test: 1000
detection:
  conf_threshold: 0.3
  nms_threshold: 0.5